### ISSUE TITLE
Feedback Abgabe 1

### ISSUE THREAD

**Issue by sebastianNoe** [theweinzierl/Kektus2#1]
Generell / Präsentation
-	Gut zum Thema geführt und die Problemstellung dargelegt
-	Navigation über readme hätte mir geholfen. Nummerierung der File Names ist aber auch in Ordnung
-	Detailiertes formulieren eurer Gedanken hilft mir sehr!

Product Vision Board
-	2019 um die 57 Mio Smartphone Nutzer – Quelle?
-	Competitors „Ausschreibungsverfahren“ welches Ausschreibungsverfahren? Welcher Auftrag? Welcher Auftraggeber?
Wirkt zu gekünstelt. Reine NPO mit potential auf Spenden u.ä. wäre in so einem Case absolut denkbar; So wirkt es ein wenig wie „zu einfach gemacht“
-	Wäre eine Vision auch über die Corona Pandemie hinweg denkbar?
-	Beschreibung der Features, etc. gut

Erfolgsermittlung / Metriken
-	Ihr schreibt zwar, dass ihr OKRs nutzt, ich denke aber, dass dies nicht der Fall ist. Stattdessen setzt ihr KPIs fest und definiert drei Grade der Zielerreichung. Was auch in Ordnung ist, nur sind OKRs etwas anderes
-	Was mir entsprechend fehlt sind Metriken zur Erfassung der Funktionalität der Lösung

Qualitätsmatrix
-	Priorisierung und Erklärungen sind konsistent

Risikoanalyse
-	Risiken sehen valide aus, aber was kann hier ausgespäht werden? Welche Daten sollen gespeichert werden?
-	Wie kann das „Risiko“ Corona Pandemie ist beendet adressiert werden? Welche weiteren Features / Funktionen könnten hier helfen?
-	Welche Nutzungs- und Bewegungsdaten sind relevant?
-	Wie können Mitigations-Strategien aussehen?

**Comment by theweinzierl** [comment]
Vielen Dank für das Feedback. Die Anmerkungen haben wir mit dem aktullen Commit "Iteration Abgabe_01" eingearbeitet, weshalb wir das Issue nun schließen.
